name: serat
description: Religious application for Muslims.

maintainers: ["Hossein HassanNejad"]
links: {"GitHub": "https://github.com/husen-hn/i_deen"}

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  dio: ^5.4.1
  quran: ^1.2.3
  shared_preferences: ^2.2.2
  fpdart: ^1.1.0
  flutter_inappwebview: ^5.8.0
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.2.2
  adivery: ^4.6.1
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.2
  motion_toast: ^2.7.10
  flutter_html: ^3.0.0-beta.2
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
  fonts:
    - family: BTitr
      fonts:
        - asset: fonts/btitr/B_Titr_Bold.ttf
    - family: BZar
      fonts:
        - asset: fonts/bzar/B_Zar.ttf
        - asset: fonts/bzar/B_Zar_Bold.ttf
    - family: Amiri
      fonts:
        - asset: fonts/amiri/Amiri-Regular.ttf
    - family: QuranTaha
      fonts:
        - asset: fonts/quran_taha/QuranTaha.ttf
    - family: AmiriQuran
      fonts:
        - asset: fonts/amiri-quran/AmiriQuran-Regular.ttf
  assets:
    - tr/original/source.json
    - tr/fa/makarem/source.json

    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/lang/fa.json
    
    - assets/namaz_logo.png
    - assets/namaz-logo-name.png
    - assets/besmelah.png
    - assets/app_icon.png
    - assets/app_icon_shadow.png
    - assets/namaz_logo_ag.png

    - assets/icons/bookmark_icon.png
    - assets/icons/lamp_icon.png
    - assets/icons/prayer_icon.png
    - assets/icons/pray_icon.png
    - assets/icons/quran.png
    - assets/icons/menu.png
    - assets/icons/menu_rtl.png
    - assets/icons/search.png
    - assets/icons/search_rtl.png
    - assets/icons/last_read.png
    - assets/icons/ayah.png
    - assets/icons/back_ltr.png
    - assets/icons/back_rtl.png
    - assets/icons/share.png
    - assets/icons/play.png
    - assets/icons/save.png
    - assets/icons/saved.png
    - assets/icons/star.png
    - assets/icons/cloud1.png
    - assets/icons/cloud2.png
    - assets/icons/cloud3.png
    - assets/icons/bin.png

    - assets/persons/ansarian.jpg
    - assets/persons/ayati.jpg
    - assets/persons/bahrampour.jpg
    - assets/persons/fooladvand.jpg
    - assets/persons/ghomshei.jpg
    - assets/persons/khorramdel.jpg
    - assets/persons/khorramshahi.jpg
    - assets/persons/makarem.jpg
    - assets/persons/moezzi.jpg
    - assets/persons/mojtabavi.jpg

    - assets/themes/light.jpg
    - assets/themes/batele.jpg
    - assets/themes/nokhodi.jpg
    - assets/themes/dark.png