name: i_deen
description: Religious application for Muslims.

maintainers: ["Hossein HassanNejad"]
links: {"GitHub": "https://github.com/husen-hn/i_deen"}

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^12.0.0
  quran: ^1.2.2
  shared_preferences: ^2.2.2
  flutter_inappwebview: ^5.8.0
  shimmer: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  fonts:
    - family: BTitr
      fonts:
        - asset: fonts/btitr/B_Titr_Bold.ttf
    - family: BZar
      fonts:
        - asset: fonts/bzar/B_Zar.ttf
        - asset: fonts/bzar/B_Zar_Bold.ttf
    - family: Amiri
      fonts:
        - asset: fonts/amiri/Amiri-Regular.ttf
        - asset: fonts/amiri/Amiri-Bold.ttf
        - asset: fonts/amiri/Amiri-BoldItalic.ttf
        - asset: fonts/amiri/Amiri-Italic.ttf
    - family: QuranTaha
      fonts:
        - asset: fonts/quran_taha/QuranTaha.ttf
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/lang/fa.json
    
    - assets/namaz_logo.png
    - assets/namaz-logo-name.png
    - assets/besmelah.png

    - assets/icons/bookmark_icon.png
    - assets/icons/lamp_icon.png
    - assets/icons/prayer_icon.png
    - assets/icons/pray_icon.png
    - assets/icons/quran_icon.png
    - assets/icons/menu.png
    - assets/icons/menu_rtl.png
    - assets/icons/search.png
    - assets/icons/search_rtl.png
    - assets/icons/last_read.png
    - assets/icons/ayah.png
    - assets/icons/back_ltr.png
    - assets/icons/back_rtl.png
    - assets/icons/share.png
    - assets/icons/play.png
    - assets/icons/save.png
    - assets/icons/star.png
    - assets/icons/cloud1.png
    - assets/icons/cloud2.png
    - assets/icons/cloud3.png