name: i_deen
description: Religious application for Muslims.

maintainers: ["Hossein HassanNejad"]
links: {"GitHub": "https://github.com/husen-hn/i_deen"}

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^12.0.0
  quran: ^1.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: fonts/vazirmatn/Vazirmatn-Regular.ttf
        - asset: fonts/vazirmatn/Vazirmatn-Bold.ttf
        - asset: fonts/vazirmatn/Vazirmatn-SemiBold.ttf
        - asset: fonts/vazirmatn/Vazirmatn-VariableFont_wght.ttf
    - family: Amiri
      fonts:
        - asset: fonts/amiri/Amiri-Regular.ttf
        - asset: fonts/amiri/Amiri-Bold.ttf
        - asset: fonts/amiri/Amiri-BoldItalic.ttf
        - asset: fonts/amiri/Amiri-Italic.ttf
  assets:
    - assets/splash.png